server:
  port: 8762

spring:
  application:
    name: service-pay
  rabbitmq:
      port: 5672
      host: localhost
      username: root
      password: 123456
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      defaultBinder: defaultRabbit
      bindings:
        inputBinding:
          group: product-deadletter-queue
        outputBinding:
          producer:
            required-groups: product-group
      rabbit:
        bindings:
          outputBinding:
            producer:
              ttl: 3000
              autoBindDlq: true
              deadLetterExchange: inputBinding
              deadLetterQueueName: inputBinding.product-deadletter-queue

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/